### ISSUE TITLE
Personal Access Tokens deprecated

### ISSUE THREAD

**Issue by amy-tabb** [nfahlgren/github_stats#1]
I've been using this repo for a while and it works great, but the personal access token method has been deprecated.  I don't know enough of the Github API to get around the Authorization HTTP header.  Do you know how to convert this repo to get it to work with the new standard?

This is the email I am getting from Github.

```
... your personal access token (get statistics for public repos) using python-requests/2.21.0 was used as part of a query parameter to access an endpoint through the GitHub API:

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
```

**Comment by nfahlgren** [comment]
Hi @amy-tabb!

I'm pretty sure I finally figured it out! I hate REST API terminology...

The quick summary is I was doing API calls like this:

```python
requests.get("https://api.github.com/repos/:repo:/traffic/clones?access_token=:token:")
```

But now we have to do it like this:

```python
requests.get("https://api.github.com/repos/:repo:/traffic/clones", 
                       headers={"Authorization": "token :token:"})
```

The good news is not much change is needed, if you update your local version of `github-stats.py` with the updated version here it should work again with no changes to your config file or anything else.

**Comment by amy-tabb** [comment]
Hi Noah, 

Thanks a lot for taking a look.  I refreshed my version of github-stats.py with yours and tested, and it works.  And thanks again for this repository.  It solves a lot of problems for me.

A
